language: scala

scala:
  - 2.11.11

cache:
  directories:
  - $HOME/.ivy2/
  - $HOME/.sbt/cache/
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jobs:
  include:
    - stage: Unit Test
    - script: ./scripts/runTest.sh
    - stage: Build Jar
    - script: ./scripts/buildFatJar.sh
    - stage: Build Container and Publish
    - script: ./scripts/publishDockerImage.sh

