sudo: required
services:
- docker
language: scala
scala:
- 2.11.11
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/cache/"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global:
  - secure: cx2cbQra7M8xrRjDGqdYwC5qpn98WSMci7RVJDjNW6k4DVrY/e6Jj13yWPp0PBneGYOSfq/sLFY+YNpJUb3iPo0bGg0rmv+evaMSN3ypixsxNDg92MG+UHTsUG1TSDaL4NOdBB07TxR5y9vXET8YS1Zb4OB+bigG8UJlpVtmJG0t+6bseAaSOLxnLBeBtrfjHRuNtjyCtdGq7fMpMWCYaw/iWKlXDdUGVMViNYn7/JHnS5PfzciPLpgogtBxCUtyGkZKOQ+Y438N0p9Sv0VgFp3ts6eJvXzIx4OaA/qoTx0giArXmi3CboDje4N1C6RNC3c3IhNqukaigv55kW7sXi47jiWoOd6Lgqqp33bX/e2oJHjR4tU5IAHGvvjTdJFpIeBhenrn6hkRrOOzVy2Th3PwmxRHZCRnh4BPST1mYsgP4Z7XEoH5ERsCiJ76WOssmrF6jPYdnKgu8ujwGljjpFr5lzS7OAPYQ3s/LidkCS7tK48yQNuaS4iKiWVYaNOC1PEWjOpZe3Bknev3Tigfd9HceZGjE5CEwIxdhzIVB4MIqc2IQeIc+kPUzrZoYN6A9G0XXPTbVPm7EG7yGU7vVM5gFgh9PZrQyqY+45KEzG6EAJdpQErrxSMqQKEgm7Lowb1057PpYyO5pwfhwKfOnPQC4J3PZkwFPA/wLzGKLoY=
  - secure: RLHBlhIHC3Te9ZNRE+u3axdW5wAHQcGVMO713WPO4QF4c8iqIrZaDwTUGO9WN7GOfESUiph/H3Qzer8agil78cQ7YbvZ2X+rt2ewPkqLLcHMQNebo2C4Uy8uRAtsuHBKAfFFla6yb3aJSIzu8lt9foQc8KYWEM2HjViGYr+Z6NoC57IQ3IkShu/1eSxbTD/OHz8y3YvPi5Dcz6+16qbRhRhlGy7pEXpr5us/fjuN5l7T+bbbSFqkZUe2hzua/1X0L/n5T5t8OClHcz+IjSBn908haViPnnDN7RiW+cTuxRPiCZ8NVNYY/8QvinAa4gXN8sxSECFPrBmS+9FMWpgVoCTVvbC7vu7jZ9hOWh9ycmObhHerRVcQ6A9oU3ou6vD8rHuJww439XBjgfeFJ3rdNAsRvA2FF6DQbfdhvyxjxnylyH2Vs3OAsQlRF8uDTUXwMb8cctWmWMg38T+lGiiKprsZkBpmI9XiT+CmlQuaUzxUkPzSBXNaAaPwbRPBWeDWHbhgyvrYFrU6uId2KZJ5sNQvFWLvDVoeoDto0yDl6bIVizEImWJy9s3dvzBh7uCH7HIpAMTnKYyVCHSOrCpqyg2rG37GGmMrzIv76UwZmhceh4whPxjRocSI4AA6KkuGLkEMlLpCPBrzM9/xS1jzJHxu6LEaEWFVXNuQiMTBLQk=
  - PACKAGE_NAME="akka-http-sample"
jobs:
  include:
  - stage: Test-Jar-Publish
    script:
    - "./scripts/runTestAndBuildArtifacts.sh"
    - export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - "./scripts/publishDockerImage.sh"
