language: scala

scala:
  - 2.11.11

cache:
  directories:
  - $HOME/.ivy2/
  - $HOME/.sbt/cache/
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  global:
    - AKKA_CONTAINER_NAME=akka-http-sample
jobs:
  include:
    - stage: Test, Jar, Publish
      script:
      - ./scripts/runTest.sh
      - ./scripts/buildFatJar.sh
      - ./scripts/publishDockerImage.sh

